# Generated by Django 4.2.1 on 2023-05-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
