# Generated by Django 5.0 on 2024-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approve',
        ),
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
